<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>

  <xacro:property name="wheelbase" value="0.240" /> 
  <xacro:property name="track" value="0.37559" /> 
  <xacro:property name="wheel_vertical_offset" value="-0.0345" />
  <xacro:property name="base_stl_vertical_offset" value="-0.0655" />

  <xacro:property name="wheel_radius" value="0.098" /> 
  <xacro:property name="wheel_width" value="0.040" /> 

  <xacro:property name="chassis_length" value="0.420" />
  <xacro:property name="chassis_width" value="0.310" /> 
  <xacro:property name="chassis_height" value="0.184" /> 

  <xacro:macro name="wheel" params="prefix *joint_pose">
    <link name="${prefix}_wheel">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="100"/>
        <inertia ixx="0.2" ixy="0" ixz="0" iyy="0.2" iyz="0" izz="0.2"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://jackal_description/meshes/jackal-wheel.stl"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <xacro:insert_block name="joint_pose"/>
      <axis xyz="0 1 0"/>
    </joint>
    <gazebo reference="${prefix}_wheel">
      <material>Gazebo/Yellow</material>
      <selfCollide>false</selfCollide>
    </gazebo>
  </xacro:macro>

  <xacro:wheel prefix="front_left">
    <origin xyz="${track/2} ${wheelbase/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
  </xacro:wheel>
  <xacro:wheel prefix="front_right">
    <origin xyz="${track/2} ${-wheelbase/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
  </xacro:wheel>
  <xacro:wheel prefix="rear_left">
    <origin xyz="${-track/2} ${wheelbase/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
  </xacro:wheel>
  <xacro:wheel prefix="rear_right">
    <origin xyz="${-track/2} ${-wheelbase/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
  </xacro:wheel>

  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="20"/>
      <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://jackal_description/meshes/jackal-base.stl"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
  </link>
  <gazebo reference="base_link">
    <selfCollide>false</selfCollide>
  </gazebo>
 
  <!-- <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="20"/>
      <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="$(find jackal_description)/meshes/jackal-base.stl"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
  </link>
  <gazebo reference="base_link">
    <selfCollide>false</selfCollide>
  </gazebo> -->
  
  <!-- <gazebo>
    <plugin name="" filename="">
      <alwaysOn>true</alwaysOn>
      <updateRate>100.0</updateRate>
      <leftJoint>left_wheel_jnt</leftJoint>
      <rightJoint>right_wheel_jnt</rightJoint>
      <wheelSeparation>${axle}</wheelSeparation>
      <wheelDiameter>${wheel_radius*2}</wheelDiameter>
      <torque>35</torque> 
    </plugin>
  </gazebo> -->
</robot>
